apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: frontend
spec:
  type: NodePort
  selector:
    app: apache
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  namespace: frontend
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: httpd-container-nautilus
          image: 2002456/httpd:latest
          ports:
            - containerPort: 80
      serviceAccountName: default