apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  selector:
    app: apache 
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30004

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache 
    spec:
      containers:
      - name: httpd-app
        image: 2002456/httpd:latest
        ports:
        - containerPort: 80
      