apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  selector:
    app: apache 
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30005

---

apiVersion: v1
kind: Pod
metadata:
  name: label-name
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache 
    spec:
      containers:
      - name: httpd-app
        image: ${env.IMAGE_NAME}
        ports:
        - containerPort: 80
      